### ISSUE TITLE
Imports failing since October 1

### ISSUE THREAD

**Issue by TheSecurityDev** [forsbergplustwo/partner-metrics#82]
I only just noticed that all the imports are failing ever since October 1. Prior to that it was working fine.

![image](https://github.com/forsbergplustwo/partner-metrics/assets/49467229/3fa5bfbe-ded7-42a8-82cb-f24b485a2064)
![image](https://github.com/forsbergplustwo/partner-metrics/assets/49467229/734ac2e9-397b-4aba-997a-50e886fed5a0)

**Comment by forsbergplustwo** [comment]
Hey @TheSecurityDev , this is almost always caused by a permissions issue. You may be receiving a new type of revenue (affiliate, theme etc.) that you were not before. Try adding the other permissions in the Shopify Partner Dashboard to your API token.

**Comment by forsbergplustwo** [comment]
@TheSecurityDev - Once you've checked the permissions, you can retry the latest import (so you don't have to wait until tomorrow). Just added that feature in #83

**Comment by TheSecurityDev** [comment]
Thanks, but it still fails 😕. I wish I could see what the error is.

**Comment by TheSecurityDev** [comment]
Also, wouldn't it be a good idea to use a version of the partner API instead of "unstable"?

**Comment by forsbergplustwo** [comment]
@TheSecurityDev - Agree, would be good to pin it to a stable version. Found the stacktrace:

```
2023-10-12 10:14:58.426 [partner_metrics_saas] worker.1 E, [2023-10-12T10:14:58.426884 #2] ERROR -- : [ActiveJob] [ImportPaymentsJob] [eac438e9-ae02-44a8-bafb-7a2017fa87a6] Error performing ImportPaymentsJob (Job ID: eac438e9-ae02-44a8-bafb-7a2017fa87a6) from Sidekiq(default) in 838.03ms: GraphQL::Client::UnimplementedFieldError (undefined field `net_amount' on TaxTransaction type. https://git.io/v1y3m):

2023-10-12 10:14:58.427 [partner_metrics_saas] worker.1 /app/app/models/import/adaptor/shopify_payments_api.rb:114:in `revenue'
2023-10-12 10:14:58.427 [partner_metrics_saas] worker.1 /app/app/models/import/adaptor/shopify_payments_api.rb:92:in `parse'
2023-10-12 10:14:58.427 [partner_metrics_saas] worker.1 /app/app/models/import/adaptor/shopify_payments_api.rb:73:in `block in stream_payments'
2023-10-12 10:14:58.427 [partner_metrics_saas] worker.1 /app/app/models/import/adaptor/shopify_payments_api.rb:72:in `each'
2023-10-12 10:14:58.427 [partner_metrics_saas] worker.1 /app/app/models/import/adaptor/shopify_payments_api.rb:72:in `stream_payments'
2023-10-12 10:14:58.427 [partner_metrics_saas] worker.1 /app/app/models/import/adaptor/shopify_payments_api.rb:50:in `block in fetch_payments'
2023-10-12 10:14:58.427 [partner_metrics_saas] worker.1 /app/app/models/import/payments_processor.rb:20:in `each'
2023-10-12 10:14:58.427 [partner_metrics_saas] worker.1 /app/app/models/import/payments_processor.rb:20:in `each'
2023-10-12 10:14:58.427 [partner_metrics_saas] worker.1 /app/app/models/import/payments_processor.rb:20:in `each_slice'
2023-10-12 10:14:58.427 [partner_metrics_saas] worker.1 /app/app/models/import/payments_processor.rb:20:in `import_new_payments'
2023-10-12 10:14:58.427 [partner_metrics_saas] worker.1 /app/app/models/import/payments_processor.rb:11:in `import!'
2023-10-12 10:14:58.427 [partner_metrics_saas] worker.1 /app/app/models/import.rb:56:in `import'
2023-10-12 10:14:58.427 [partner_metrics_saas] worker.1 /app/app/jobs/import_payments_job.rb:6:in `perform'
```

**Comment by forsbergplustwo** [comment]
@TheSecurityDev - This is being deployed now, so give it 5 mins then try again. If you continue to have issues, feel free to re-open this.

**Comment by TheSecurityDev** [comment]
Still not working 😕

**Comment by forsbergplustwo** [comment]
@TheSecurityDev - Here's the stacktrace:

```

2023-10-12 11:46:17.446 [partner_metrics_saas] worker.1 pid=2 tid=1ibm WARN: GraphQL::Client::UnfetchedFieldError: unfetched field `amount' on #<Class:0x00007fb1a63edb68> type. https://git.io/v1y3U


2023-10-12 11:46:17.446 [partner_metrics_saas] worker.1 pid=2 tid=1ibm WARN: app/models/import/adaptor/shopify_payments_api.rb:112:in `revenue'
2023-10-12 11:46:17.446 [partner_metrics_saas] worker.1 app/models/import/adaptor/shopify_payments_api.rb:92:in `parse'
2023-10-12 11:46:17.446 [partner_metrics_saas] worker.1 app/models/import/adaptor/shopify_payments_api.rb:73:in `block in stream_payments'
2023-10-12 11:46:17.446 [partner_metrics_saas] worker.1 app/models/import/adaptor/shopify_payments_api.rb:72:in `each'
2023-10-12 11:46:17.446 [partner_metrics_saas] worker.1 app/models/import/adaptor/shopify_payments_api.rb:72:in `stream_payments'
2023-10-12 11:46:17.446 [partner_metrics_saas] worker.1 app/models/import/adaptor/shopify_payments_api.rb:50:in `block in fetch_payments'
2023-10-12 11:46:17.446 [partner_metrics_saas] worker.1 app/models/import/payments_processor.rb:20:in `each'
2023-10-12 11:46:17.446 [partner_metrics_saas] worker.1 app/models/import/payments_processor.rb:20:in `each'
2023-10-12 11:46:17.446 [partner_metrics_saas] worker.1 app/models/import/payments_processor.rb:20:in `each_slice'
2023-10-12 11:46:17.446 [partner_metrics_saas] worker.1 app/models/import/payments_processor.rb:20:in `import_new_payments'
2023-10-12 11:46:17.446 [partner_metrics_saas] worker.1 app/models/import/payments_processor.rb:11:in `import!'
2023-10-12 11:46:17.446 [partner_metrics_saas] worker.1 app/models/import.rb:56:in `import'
2023-10-12 11:46:17.446 [partner_metrics_saas] worker.1 app/jobs/import_payments_job.rb:6:in `perform'
```

Issue is I don't have the same API responses as you do, and so I'm not able to test to get the same failure.

Strangely though, we are not asking for the TaxTransaction nodes in our GraphQL calls, so it actually shouldn't be in the responses at all. Anyway, will rollback to "2023-07" to see if it helps.

**Comment by TheSecurityDev** [comment]
Yes I'm guessing something changed in the API. Or perhaps I have a different type of transaction that occurred around that date. Maybe I should make the GraphQL requests manually and play around with it.

**Comment by TheSecurityDev** [comment]
The only unusual thing is I applied a large app credit ($50) on Sept 30 as a partial refund for someone who was on an annual subscription.

**Comment by TheSecurityDev** [comment]
Could you log the exact transaction ID, name, date, etc. to make it easier to spot which one is failing?

**Comment by TheSecurityDev** [comment]
Still doesn't work.

Perhaps you need to fetch that here: https://github.com/forsbergplustwo/partner-metrics/blob/main/app/models/graphql/transactions_query.rb#L101

Is there a way to tell what type the transaction is? Maybe you can check for and skip TaxTransactions. But I see what you mean, it looks like it shouldn't be fetching them in the first place. Perhaps something in my transaction data got messed up on Shopify's side.

**Comment by forsbergplustwo** [comment]
Yeah, something weird going on.. as they shouldn't be there in the first place.

I've removed the inclusion of "TaxTransactions" from the case statements, so we are back where we started, but now with an earlier API version.

If that doesn't help, it would be great if you could try it out locally and check the exact responses you are getting from the API 😊

**Comment by TheSecurityDev** [comment]
I could try, but I don't know anything about Ruby and don't have the environment set up. For now I'm just going to make the GraphQL request on my end.

**Comment by TheSecurityDev** [comment]
So I can confirm that it's including the TaxTransaction in the response with the following GraphQL request:

```gql
  query($createdAtMax:DateTime, $first: Int) {
    transactions(createdAtMax:$createdAtMax, first: $first) {
      edges {
        cursor
        node {
          id,
          createdAt,
          # Apps
          ... on AppSubscriptionSale {
            billingInterval,
            netAmount {
              amount
            },
            app {
              name
            },
            shop {
              myshopifyDomain
            }
          },
          ... on AppOneTimeSale {
            netAmount {
              amount
            },
            app {
              name
            },
            shop {
              myshopifyDomain
            }
          },
          ... on AppSaleAdjustment {
            netAmount {
              amount
            },
            app {
              name
            },
            shop {
              myshopifyDomain
            }
          },
          ... on AppSaleCredit {
            netAmount {
              amount
            },
            app {
              name
            },
            shop {
              myshopifyDomain
            }
          },
          ... on AppUsageSale {
            netAmount {
              amount
            },
            app {
              name
            },
            shop {
              myshopifyDomain
            }
          },
          # skipped LegacyTransaction, not sure what it is
          ... on ReferralAdjustment {
            amount {
              amount
            },
            shop {
              myshopifyDomain
            }
          },
          ... on ReferralTransaction {
            amount {
              amount
            },
            shopNonNullable: shop {
              myshopifyDomain
            }
          },
          ... on ServiceSale {
            netAmount {
              amount
            },
            shop {
              myshopifyDomain
            }
          },
          ... on ServiceSaleAdjustment {
            netAmount {
              amount
            },
            shop {
              myshopifyDomain
            }
          },
          # skipped TaxTransaction
          ... on ThemeSale {
            netAmount {
              amount
            },
            theme {
              name # may not match CSV import behaviour
            },
            shop {
              myshopifyDomain
            }
          },
          ... on ThemeSaleAdjustment {
            netAmount {
              amount
            },
            theme {
              name # may not match CSV import behaviour
            },
            shop {
              myshopifyDomain
            }
          },
        }
      },
      pageInfo {
          hasNextPage
      }
    }
  }
  ```
Variables:
```json
{
  "createdAtMax": "2023-10-02T00:00:00Z"
}
```

Response:
```json
        {
          "cursor": "eyJwYXJ0bmVyX3JlY2VpdmFibGVfY3JlYXRlZF9hdCI6MTY5NjEyNzY0NzAwMCwiaWQiOiIyNTE3NDExMzAtMSJ9",
          "node": {
            "id": "gid://partners/TaxTransaction/251741130-1",
            "createdAt": "2023-10-01T02:34:07.000000Z"
          }
        },
        {
          "cursor": "eyJwYXJ0bmVyX3JlY2VpdmFibGVfY3JlYXRlZF9hdCI6MTY5NjEyNzY0NzAwMCwiaWQiOiIyNTE3NDExMzAtMCJ9",
          "node": {
            "id": "gid://partners/TaxTransaction/251741130-0",
            "createdAt": "2023-10-01T02:34:07.000000Z"
          }
        },
```

**Comment by TheSecurityDev** [comment]
It looks like it got added twice for some reason, so the ID got messed up. This is probably why it's not filtering out those IDs correctly.

I think it should be enough to check the ID for `TaxTransaction` and and ignore that item if so.

**Comment by forsbergplustwo** [comment]
Thanks @TheSecurityDev , that's a big help.. will take another look early next week :)

**Comment by forsbergplustwo** [comment]
@TheSecurityDev - The app should skip these problematic transaction types now. If you still have any issues, do feel free to re-open 😊

**Comment by TheSecurityDev** [comment]
Great, it's working now! Thank you so much 😊
